name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - run: bun i --frozen-lockfile
      - run: bun run build

      - name: Publish vite-plugin-bun-csp
        if: startsWith(github.ref, 'refs/tags/vite-plugin-bun-csp-')
        run: |
          cd ./packages/vite-bun
          bun pm pack --quiet
          npm publish --provenance --access public *.tgz
          rm *.tgz

      - name: Publish csp-bun-cli
        if: startsWith(github.ref, 'refs/tags/csp-bun-cli-')
        run: |
          cd ./packages/cli-bun
          bun pm pack --quiet
          npm publish --provenance --access public *.tgz
          rm *.tgz
